name: Python Apply
 
on:
  pull_request:
    types: [closed]
 
jobs:
  build-matrix:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
 
      - name: Debug labels
        run: |
          echo "Raw labels: ${{ join(github.event.pull_request.labels.*.name, ' | ') }}"
 
      - name: Set matrix
        id: set-matrix
        run: |
          # Define environments you want to target
          MATRIX='["dev1","dev2"]'
          echo "Initial matrix: $MATRIX"
 
          # Get PR labels as a string
          labels="${{ join(github.event.pull_request.labels.*.name, ' ') }}"
          echo "Labels string: $labels"
 
          # Filter out envs that have a no-changes label
          FILTERED=$(echo "$MATRIX" | jq -c \
            "[ .[] | select( (\"$labels\" | test(\"aws[_ ]\" + . + \"/no-changes\")) | not ) ]")
 
          echo "Filtered matrix: $FILTERED"
          echo "matrix=$FILTERED" >> $GITHUB_OUTPUT
 
  python-apply:
    needs: build-matrix
    if: ${{ needs.build-matrix.outputs.matrix != '[]' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: ${{ fromJson(needs.build-matrix.outputs.matrix) }}
 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
 
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
 
      - name: Install dependencies
        run: |
          echo "Installing dependencies for environment: ${{ matrix.env }}"
          python -m pip install --upgrade pip
          pip install pytest
 
      - name: Run tests
        run: |
          echo "Running tests in environment: ${{ matrix.env }}"
          cd src
          python -m pytest addition.py
 
      - name: Show script output
        run: |
          echo "Script output for environment: ${{ matrix.env }}"
          python addition.py
