name: Python Apply
 
on:
  pull_request:
    types: [closed]
 
jobs:
  python-apply:
    #if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'ok')
    #if: github.event.pull_request.merged == true && !contains(join(github.event.pull_request.labels.*.name, ','), 'no-changes')
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [dev1, dev2]
 
    steps:
      #- name: Skip if env has no-changes label
        # if: contains(github.event.pull_request.labels.*.name, format('aws_${{ matrix.env }}/no-changes')) == true
        # run: |
        #   echo "Skipping APPLY for ${{ matrix.env }} because label aws_${{ matrix.env }}/no-changes is present"
        #   exit 0
        
      - name: Check if this env should be skipped
        run: |
          labels="${{ join(github.event.pull_request.labels.*.name, ' ') }}"
          if [[ "$labels" == *"aws_${{ matrix.env }}/no-changes"* ]]; then
            echo "Skipping APPLY for ${{ matrix.env }} because label aws_${{ matrix.env }}/no-changes is present"
            exit 78
          fi
          
      - name: Checkout
        uses: actions/checkout@v4
 
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
 
      - name: Run tests (Apply stage)
        #run: pytest addition.py
        run: |
          echo "Running test in env: ${{ matrix.env }}"
          cd src
          python -m pytest addition.py
          python addition.py
