name: Python Apply
 
on:
  pull_request:
    types: [closed]
 
jobs:
  python-apply:
    #if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'ok')
    if: github.event.pull_request.merged == true && !contains(join(github.event.pull_request.labels.*.name, ','), 'no-changes')
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
 
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
 
      - name: Run tests (Apply stage)
        #run: pytest addition.py
        run: |
          cd src
          python -m pytest addition.py
