name: Python Plan

on:
  pull_request:
    types: [labeled, opened, synchronize]

jobs:
  python-plan:
    runs-on: ubuntu-latest    
    strategy:
      matrix:
        env: [dev1, dev2]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
